/* CPYHDR { */
/*
 * SPDX-FileCopyrightText: © 2015 Marco Frigerio
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * This file is part of the 'iit-rbd' library.
 */
/* } CPYHDR */
#ifndef IIT_RBD_H_
#define IIT_RBD_H_

#include <Eigen/Dense>
#define EIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET 1
#include <Eigen/Sparse>


namespace iit {
/**
 * This namespace contains some basic types and functions related to spatial
 * vectors and Rigid Body Dynamics (RBD).
 *
 * This code has been developed to provide basic types and general utilities to
 * be used in turn by the C++ classes generated by the Robotics Code Generator
 * (RobCoGen). That is, the code is just meant to be a common, generic facility
 * for all the robot-specific code that RobCoGen can generate.
 *
 * In other words, the primary target of the \c iit_rbd library is not to
 * provide a comprehensive object-oriented implementation of concepts of
 * rigid-body dynamics and spatial vectors, for end-user applications. Some
 * of such concepts do appear in this software, although the implementation is
 * relatively simple.
 * However, the library may very well be used in custom code that needs e.g.
 * a type for spatial vectors or for the spatial 6x6 inertia tensor.
 */
namespace rbd {

/**
 * \defgroup rbd-core RBD Core
 * Main, basic data types and functions
 *
 * All the types are templated on the Scalar type. There are two ways of
 * defining a complete type in client code. For individual types one can use
 * something like this:
 * \code
 *      typedef iit::rbd::Velocity< float > myVelocity;
 * \endcode
 *
 * An alternative, maybe neater in the case of multiple types, is the following:
 * \code
 *      typedef float Scalar;
 *      typedef iit::rbd::Core< Scalar > mycore;
 *
 *      using Matrix33 = mycore::Matrix33;
 *      using Vector3  = mycore::Vector3;
 *      using Velocity = mycore::VelocityVector;
 *      // etc.
 * \endcode
 * @{
 */

/**
 * \name General matrix types
 */
///@{
// Use alias templates to limit the references to 'Eigen' to this header

template<typename Derived>
using MatrixBase = Eigen::MatrixBase< Derived >;

template<typename Scalar, int R, int C>
using PlainMatrix = Eigen::Matrix< Scalar, R, C >;

template<typename XprType, int R, int C>
using MatrixBlock = Eigen::Block< XprType, R, C >;

template<typename Scalar>
using SparseMatrix = Eigen::SparseMatrix<Scalar>;

template<typename Scalar>
using SparseVector = Eigen::SparseVector<Scalar>;
///@}


/**
 * \name Generators of individual core types
 *
 * These aliases are useful when one or few types are needed, given a Scalar.
 */
///@{
#define TPL template<typename S>
TPL using Mat33    = PlainMatrix<S,3,3>;
TPL using Mat66    = PlainMatrix<S,6,6>;
TPL using Vec3     = PlainMatrix<S,3,1>;
TPL using Vec6     = PlainMatrix<S,6,1>;
TPL using Velocity = Vec6<S>;
TPL using Force    = Vec6<S>;
TPL using Part3    = MatrixBlock< Vec6<S>, 3,1>;     ///< a 3D subvector of a 6D vector
TPL using Part3Const = MatrixBlock< const Vec6<S>, 3,1>;///< a const 3D subvector of a 6D vector
#undef TPL
///@}


/**
 * A container of core types, templated on the scalar type.
 *
 * \tparam SCALAR the numerical type for scalar values
 */
template<typename SCALAR>
struct Core
{
    using Scalar = SCALAR;

    /** \name Basic matrix types */
    ///@{
    using Matrix33 = Mat33<Scalar>;
    using Matrix66 = Mat66<Scalar>;
    using Vector3  = Vec3<Scalar>;
    using Vector6  = Vec6<Scalar>;
    ///@}

    /**
     * \name 6D vectors "à la Featherstone"
     * Types of vectors used in dynamics computations.
     * The capital 'D' stands for Dimension, not double !
     */
    ///@{
    using Vector6D       = Vector6;
    using Column6D       = Vector6D;
    using VelocityVector = Vector6D;
    using MotionVector   = Vector6D;
    using ForceVector    = Vector6D;

    using Part3D      = MatrixBlock<      Vector6D,3,1>;  ///< a 3D subvector of a 6D vector
    using Part3DConst = MatrixBlock<const Vector6D,3,1>;  ///< a const 3D subvector of a 6D vector
    ///@}
};


/**
 * \name Core types using double as scalar
 *
 * Explicit instantiation of all the various matrix types using the standard
 * \c double as the scalar type. These definitions are included for backward
 * compatibility with client code using prior non-templated version of this
 * library.
 *
 * See Core.
 */
///@{
typedef Core<double> Cored;

using Matrix33d = Cored::Matrix33;
using Vector3d  = Cored::Vector3;
using Matrix66d = Cored::Matrix66;
using Vector6d  = Cored::Vector6;

using Vector6D       = Cored::Vector6D;
using VelocityVector = Cored::VelocityVector;
using ForceVector    = Cored::ForceVector;

using Part3D      = Cored::Part3D;
using Part3DConst = Cored::Part3DConst;

using Column6d = Cored::Column6D;  // an alias

using SparseMatrixd = SparseMatrix<double>;
using SparseColumnd = SparseVector<double>;
///@}

/**
 *  \name 6D vectors accessors
 *  These functions allow to access the linear and the angular
 *  coordinates of motion/force vectors.
 */
///@{
/**
 * The 3-coordinate vector with the angular components (angular
 * velocity or torque) of the given 6D vector.
 */
template<typename Scalar>
Part3<Scalar> angularPart(Vec6<Scalar>& f) {
    return f.template topRows<3>();
}

/**
 * The 3-coordinate vector with the linear components (linear
 * velocity or force) of the given 6D vector.
 */
template<typename Scalar>
Part3<Scalar> linearPart(Vec6<Scalar>& f) {
    return f.template bottomRows<3>();
}
template<typename Scalar>
Part3Const<Scalar> angularPart(const Vec6<Scalar>& f) {
    return f.template topRows<3>();
}
template<typename Scalar>
Part3Const<Scalar> linearPart(const Vec6<Scalar>& f) {
    return f.template bottomRows<3>();
}
///@}



/**
 * \name Vector coordinates
 * Constants to index either 6D or 3D coordinate vectors.
 */
///@{
enum Coords3D { X=0, Y, Z};
/// To be used with 6D vectors. 'A' stands for angular, 'L' for linear.
enum Coords6D { AX=0, AY, AZ, LX, LY, LZ };
///@}

///@} // end of implicit in-group elements [Doxygen]

/**
 * The Earth gravitational acceleration constant.
 * This value should always be positive, so that an application
 * chooses the sign according to its conventions.
 */
constexpr double g{9.80665};

}
}


#endif /* IIT_RBD_H_ */
