/* CPYHDR { */
/*
 * SPDX-FileCopyrightText: © 2015 Marco Frigerio
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * This file is part of the 'iit-rbd' library.
 */
/* } CPYHDR */

#ifndef _IIT_ROBCOGEN_TEST_DYNAMICS_CONSISTENCY_
#define _IIT_ROBCOGEN_TEST_DYNAMICS_CONSISTENCY_

#include <iostream>
#include <ctime>

#include <iit/rbd/rbd.h>
#include <iit/rbd/utils.h>
#include <iit/robcogen/scalar/internals.h>

#include "../utils.h"

namespace iit {
namespace robcogen {

/**
 * Test routines for the C++ code generated by RobCoGen
 */
namespace test {

namespace {

template<typename ROB>
using Scalar = typename internal::ScalarTraitsSelector< ROB >::trait::Scalar;

}
/**
 * \name Dynamics consistency tests
 * These functions compare the output of the dynamics solvers to verify
 * they are consistent.
 *
 * Comparison results are simply reported by printing the difference between
 * two values, which should be a zero vector.
 *
 * The tests involve the quantities of the well known dynamics equation
 * \f[ M \ddot{q} + C + G = \tau \f]
 * which are computed in various ways using the solvers for inverse-dynamics,
 * forward-dynamics and the Joint Space Inertia Matrix (JSIM), using random
 * values for the input variables.
 *
 * The general test strategies are the following:
 * - (a) Inverse dynamics:
 *    use the dedicated methods of the inverse dynamics engine to compute
 *    the gravity and Coriolis joint forces (\f$C+G\f$), and then compare the
 *    results with the method for the total joint forces (\f$\tau\f$).
 *
 * - (b) Inverse dynamics and JSIM:
 *    compute explicitly the inertia matrix (\f$M\f$) and check that it
 *    satisfies the dynamics equation, using values for the joint space
 *    acceleration and force obtained with inverse dynamics.
 *
 * - (c) Inverse and forward dynamics:
 *    use the forward dynamics engine to compute the joint accelerations,
 *    using the same position and velocity inputs and joint forces output from
 *    inverse dynamics. The computed accelerations ought to be equal to the
 *    input ones used with inverse dynamics. In other words, make sure that
 *    inverse and forward dynamics are actually complementary.
 *
 * - (d) Forward dynamics and JSIM inverse:
 *    compare the joint accelerations computed with the forward dynamics and
 *    with the inverse of the joint space inertia matrix \f$M^{-1}\f$; the
 *    joint velocities are set to zero, the gravity terms \f$G\f$ are
 *    computed with the inverse dynamics engine. The accelerations are
 *    computed with
 *    \f$ \ddot{q} = M^{-1} (\tau - G) \f$
 *
 * \tparam RT the class Traits for a robot, as generated by RobCoGen
 */
///@{
/**
 * Test consistency of the inverse dynamics solver for fixed-base robots.
 * Implements test (a).
 */
template<class RT>
void fixedBaseID( typename RT::InvDynEngine& invDynEngine)
{
    iit::rbd::Utils::CwiseAlmostZeroOp< Scalar<RT> > approx(1E-5);
    typename RT::JointState q, qd, c, g, tau, diff;
    robcogen::utils::rand_jstate<RT>(q);
    robcogen::utils::rand_jstate<RT>(qd);

    invDynEngine.G_terms(g, q);
    invDynEngine.C_terms(c, q, qd);
    invDynEngine.id(tau, q, qd, RT::JointState::Zero());
    diff = tau - c - g;
    std::cout << "Inverse dynamics (consistency of the routines to compute gravity and Coriolis terms separately):" << std::endl;
    std::cout << diff.transpose().unaryExpr(approx) << std::endl << std::endl;
}

/**
 * Test consistency of the inverse dynamics solver for floating-base robots.
 * Implements test (a) plus an extra consistency tests between the hybrid and
 * fully-actuated solvers.
 */
template<class RT>
void floatingBaseID( typename RT::InvDynEngine& invDynEngine)
{
    iit::rbd::Utils::CwiseAlmostZeroOp< Scalar<RT> > approx(1E-10);
    typename RT::JointState q, qd, qdd, tau_g, tau_c, tau, tau2;
    iit::rbd::VelocityVector base_v, base_a, gravity;
    iit::rbd::ForceVector base_wrench_g, base_wrench_c, base_wrench;

    robcogen::utils::rand_jstate<RT>(q, qd, qdd);
    iit::rbd::Utils::randomVec(base_v);
    iit::rbd::Utils::randomGravity(gravity);

    invDynEngine.setJointStatus(q);
    invDynEngine.G_terms_fully_actuated(base_wrench_g, tau_g, gravity);
    invDynEngine.C_terms_fully_actuated(base_wrench_c, tau_c, base_v, qd);
    invDynEngine.id_fully_actuated(base_wrench, tau, gravity, base_v,
                iit::rbd::VelocityVector::Zero(), qd,  RT::JointState::Zero());

    std::cout << "Consistency of the routines to compute gravity and Coriolis terms separately - fully actuated case:" << std::endl;
    std::cout << (tau - tau_c - tau_g).transpose().unaryExpr(approx) << std::endl << std::endl;

    invDynEngine.id(tau, base_a,  gravity, base_v, qd, qdd);
    invDynEngine.id_fully_actuated(base_wrench, tau2, gravity, base_v, base_a, qd, qdd);

    std::cout << "Consistency between fully-actuated-floating-base inverse dynamics and hybrid dynamics:" << std::endl;
    std::cout << (tau - tau2).transpose().unaryExpr(approx) << std::endl << std::endl;
}

/**
 * Test consistency between inverse dynamics and the joint space inertia matrix
 * for fixed-base-robot solvers.
 * This function implements test (b), but
 * tests the computation of L for the L^T L factorization.
 */
template<class RT>
void fixedBaseJSIM(typename RT::InvDynEngine& invDynEngine,
                   typename RT::JSIM&         jsim)
{
    iit::rbd::Utils::CwiseAlmostZeroOp< Scalar<RT> > approx(1E-5);
    typename RT::JointState q, qdd, g, tau, diff;
    robcogen::utils::rand_jstate<RT>(q, g, qdd);

    invDynEngine.id(tau, q, RT::JointState::Zero(), qdd);
    invDynEngine.G_terms(g, q);
    diff = tau - g - (jsim(q) * qdd);
    std::cout << "Inverse dynamics and JSIM:" << std::endl;
    std::cout << diff.transpose().unaryExpr(approx) << std::endl << std::endl;

    jsim.computeL();
    typename RT::JSIM::MatrixType L = jsim.getL();
    typename RT::JSIM::MatrixType Mdiff = jsim - L.transpose()*L;
    std::cout << "JSIM and its LTL factorization:" << std::endl;
    std::cout << Mdiff.unaryExpr(approx) << std::endl << std::endl;

    jsim.computeInverse();
    typename RT::JSIM::MatrixType inv = jsim.getInverse();
    Mdiff = jsim * inv;
    std::cout << "JSIM and its inverse (identity expected):" << std::endl;
    std::cout << Mdiff.unaryExpr(approx) << std::endl << std::endl;
}

/**
 * Test consistency between inverse dynamics and the joint space inertia matrix
 * for floating-base-robot solvers.
 * This function implements test (b), but
 * also tests the computation of L for the L^T L factorization of the
 * actual-joints block of the inertia matrix.
 */
template<class RT>
void floatingBaseJSIM(
    typename RT::InvDynEngine& invDynEngine,
    typename RT::JSIM&         jsim)
{
    iit::rbd::Utils::CwiseAlmostZeroOp< Scalar<RT> > approx(1E-10);
    typename RT::JointState q, _, qdd, tau_g, tau, diff;
    iit::rbd::VelocityVector base_a, base_a_fd, gravity;
    iit::rbd::ForceVector base_wrench_g, base_wrench, diff_wrench;

    robcogen::utils::rand_jstate<RT>(q, _, qdd);
    iit::rbd::Utils::randomVec(base_a);
    iit::rbd::Utils::randomGravity(gravity);

    invDynEngine.setJointStatus(q);
    invDynEngine.G_terms_fully_actuated(base_wrench_g, tau_g, gravity);
    invDynEngine.id_fully_actuated(base_wrench, tau, gravity, iit::rbd::VelocityVector::Zero(), base_a, RT::JointState::Zero(), qdd);
    jsim(q);

    diff = tau - (jsim.getF().transpose()*base_a + jsim.getFixedBaseBlock()*qdd + tau_g);
    diff_wrench = base_wrench -
            (jsim.getWholeBodyInertia() * base_a +
                    jsim.getF() * qdd + base_wrench_g);

    std::cout << "Fully-actuated-floating-base inverse dynamics and JSIM:" << std::endl;
    std::cout <<
            diff_wrench.transpose().unaryExpr(approx) << "   " <<
            diff.transpose().unaryExpr(approx) << std::endl << std::endl;

    jsim.computeL();
    typename RT::JSIM::RealJointsBlock_matrix_t L = jsim.getL();
    typename RT::JSIM::RealJointsBlock_matrix_t Mdiff = jsim.getFixedBaseBlock() - L.transpose()*L;
    std::cout << "JSIM and its LTL factorization:" << std::endl;
    std::cout << Mdiff.unaryExpr(approx) << std::endl << std::endl;

    jsim.computeInverse();
    typename RT::JSIM::RealJointsBlock_matrix_t inv = jsim.getInverse();
    Mdiff = jsim.getRealJointsBlock() * inv;
    std::cout << "actuated-joints-block of the JSIM and its inverse (identity expected):" << std::endl;
    std::cout << Mdiff.unaryExpr(approx) << std::endl << std::endl;
}

/**
 * Test consistency of the inverse and forward dynamics solvers.
 * This function implements test (c).
 */
template<class RT>
void fixedBaseFD( typename RT::FwdDynEngine& solverFD,
                  typename RT::InvDynEngine& solverID)
{
    iit::rbd::Utils::CwiseAlmostZeroOp< Scalar<RT> > approx(1E-5);
    typename RT::JointState q, qd, qdd, qdd_fd, tau, diff;
    robcogen::utils::rand_jstate<RT>(q, qd, qdd);

    solverID.id(tau, q, qd, qdd);
    solverFD.fd(qdd_fd, q, qd, tau);
    diff = qdd - qdd_fd;
    std::cout << "Forward (and inverse) dynamics:" << std::endl;
    std::cout << diff.transpose().unaryExpr(approx) << std::endl << std::endl;
}


/**
 * Test consistency of the inverse and forward dynamics solvers for a floating
 * base robot.
 * This function implements test (c).
 */
template<class RT>
void floatingBaseFD( typename RT::FwdDynEngine& solverFD,
                     typename RT::InvDynEngine& solverID)
{
    iit::rbd::Utils::CwiseAlmostZeroOp< Scalar<RT> > approx(1E-5);
    typename RT::JointState q, qd, qdd, qdd_fd, tau, diff_qdd;
    iit::rbd::VelocityVector base_v, base_a, base_a_fd, diff_base_a, gravity;

    robcogen::utils::rand_jstate<RT>(q, qd, qdd);
    iit::rbd::Utils::randomVec(base_v);
    iit::rbd::Utils::randomGravity(gravity);

    solverID.id(tau, base_a,  gravity, base_v, q, qd, qdd);
    solverFD.fd(qdd_fd, base_a_fd, base_v, gravity, q, qd, tau);

    diff_qdd    = qdd - qdd_fd;
    diff_base_a = base_a - base_a_fd;

    std::cout << "Forward (and inverse) dynamics:" << std::endl;
    std::cout << diff_base_a.transpose().unaryExpr(approx) << "   " <<
            diff_qdd.transpose().unaryExpr(approx) << std::endl << std::endl;
}

/**
 * Test of the inverse of the Joint Space Inertia Matrix for a fixed-base
 * robot.
 *
 * This function performs test (d) described in the general comments
 * (above).
 *
 * \param fwdDynEngine an instance of the forward dynamics class of the robot
 * \param invDynEngine an instance of the inverse dynamics class
 * \param jsim an instance of the Joint Space Inertia Matrix
 */
template<class RT>
void fixedBaseJSIMInverse(
        typename RT::FwdDynEngine& fwdDynEngine,
        typename RT::InvDynEngine& invDynEngine,
        typename RT::JSIM&         jsim)
{
    iit::rbd::Utils::CwiseAlmostZeroOp< Scalar<RT> > approx(1E-5);
    typename RT::JointState q, qd, qdd, g, tau, diff;
    robcogen::utils::rand_jstate<RT>(q, qdd, tau);

    invDynEngine.G_terms(g, q);
    fwdDynEngine.fd(qdd, q, RT::JointState::Zero(), tau);
    jsim(q);
    jsim.computeL();
    jsim.computeInverse();
    diff = qdd - jsim.getInverse() * (tau - g);
    std::cout << "JSIM inverse:" << std::endl;
    std::cout << diff.transpose().unaryExpr(approx) << std::endl << std::endl;
}
///@}

}
}
}

#endif
